# Generated by Django 3.0.3 on 2020-03-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='profilePic',
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='farms'),
        ),
    ]
